version: '3.3'
services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    ports:
      - 1433:1433
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd